name: OOPGRADE/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: ["2.7", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.python-version != '2.7'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python 2
      if: matrix.python-version == '2.7'
      run: |
          sudo apt update
          sudo apt install python2 python-pip
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
          printf '1\n' | sudo update-alternatives --config python
          cd /usr/bin
          sudo ln -s /usr/bin/pip2 ./pip

    - name: Upgrade pip
      run: |
        pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Run test
      run: |
        mamba